### ISSUE TITLE
Label highlight

### ISSUE THREAD

**Issue by stef-k** [Wikiki/bulma-checkradio#4]
I do not know if this is intentional but when clicking the element rapidly, the text in the label gets highlighted.

![image](https://user-images.githubusercontent.com/5731388/29983363-28c2d324-8f5e-11e7-858f-24acf6e2cdf4.png)

If it is not intentional behavior then it can be fixed with the following 

```css
.is-checkbox[type=checkbox]+label, .is-radio[type=radio]+label {
  user-select: none;
}
```

[Browser support for this rule is at 88.69%](http://caniuse.com/user-select-none/embed/description&links)
